# Generated by Django 4.0.2 on 2022-02-11 22:44

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100)),
                ('course_tag', models.CharField(max_length=15)),
                ('course_credits', models.IntegerField()),
                ('desciption', models.TextField()),
                ('terms', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=6), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('degree_id', models.AutoField(primary_key=True, serialize=False)),
                ('degree_type', models.CharField(max_length=50)),
                ('degree_name', models.CharField(max_length=50)),
                ('school', models.CharField(max_length=100)),
                ('term', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('curr_plan', models.JSONField()),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MakeMyDegree.degree')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('rule', models.CharField(max_length=50)),
                ('degree_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MakeMyDegree.degree')),
            ],
        ),
        migrations.CreateModel(
            name='Requisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisite_type', models.CharField(max_length=50)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='MakeMyDegree.course')),
                ('requisite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisites', to='MakeMyDegree.course')),
            ],
        ),
    ]
