# Generated by Django 4.0.2 on 2022-04-06 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MakeMyDegree', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='degree_id',
            new_name='degree',
        ),
    ]
