# Generated by Django 4.0.2 on 2022-04-19 16:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MakeMyDegree', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='terms',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=6), blank=True, default=list, size=None),
        ),
    ]
