# Generated by Django 4.0.2 on 2022-02-22 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MakeMyDegree', '0003_alter_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='desciption',
            new_name='description',
        ),
    ]
